
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozdofjghekhuqrwidwsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96ZG9mamdoZWtodXFyd2lkd3N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTI5NDEsImV4cCI6MjA2MjEyODk0MX0.1DTbw9K_I6Qz4tKl09U2qJTaSBQ0oc1hP3YvLBIrZ-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
  }
});
